[[redirects]]
  from = "/api/*"
  to = "https://backend-licenta-i0lr.onrender.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';"